server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  environment: hmily-test
  data-center: spirit-center
      
      
